#+title: Queueing Theory and Simulation, lecture 3
#+author: Nicky van Foreest
#+date: \today
#+email: n.d.van.foreest@rug.nl

#+options: H:2 email:t num:t tex:t toc:t LaTeX:t
#+language: en
#+startup: beamer
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [bigger]
# +beamer_theme: Copenhagen
#+beamer_theme: metropolis

#+include: preamble.org


* General things
** General things
- assignments: hope you enjoy them. We do one per week, even though most is on github already
- assignments: making groups works?
- Book: keep up with the exercises.
- book format (main text, comments and references to exercises in the margin.)


* Notation for queues

** Continuous time, multiserver queue

- Job $k$ sees, upon arrival, a waiting time $w_{k,i}$ at queue $i$.
- $m$ servers
- $w_{k}=(w_{k,1},\ldots, w_{k,m})$,
- $I$ represents here a vector $(1,1,\ldots,1)$.
- $e_{k}$ is \(k\)th unit vector, i.e., all zeros with $1$ at \(k\)th place

\begin{align}
\label{eq:6}
s_{k} &= \argmin_{i}\{w_{k,i}\} \\
w_{k+1} &= [w_{k} + S_{k} e_{s_{k}} - X_{k+1}I]^{+},\\
W_{k} &= w_{k, s_{k}}
\end{align}

$\implies$ $\{X_{k}\}$, $\{S_{k}\}$ and $m$ suffice construct the queueing process.

** Kendall's  notation
- M/M/1
- M/M/c
- G/G/c
- D/D/1

* Random walk
** Applications
- insurance
- production inventory control
- queueing

It's all the `same' thing we study.

** Elegant recursion

\begin{align}
Z_{k} &= Z_{k-1} + a_{k}-c_{k}\\
L_k &= [L_{k-1} + a_{k} - c_{k}]^{+} = [L_{k-1} + Z_{k} - Z_{k-1}]^{+} \\
L_{k} &= Z_{k} - \min_{1\leq i\leq k} Z_{k} \wedge 0
\end{align}

Nice formula, but still a recursion

** Useful and useless

- Can we find a closed form solution, something like $x_{t} = x_{0} + v_{0}t - g t^{2}/2$ for the height of bullet in a homogeneous gravitational field (and no friction)? \pause No, disappointingly.
- We have to drop the time-dependent analysis
- Henceforth in the course we  concentrate on finding formulas compute/estimate time-average waiting times, e.g, \(\E{W}\), or $\E{\1{W\geq x}}$.

* Rest of the course
** Next lecture
- Concept of rate
- Stability
- Convergence to stationary state
** lectures next week
- One of the most beautiful (?) formulas of probability, Sakasegawa's approximation for the average waiting time in an G/G/c queue.
- Application to many different practically useful queueing systems.
** later lectures
- Use sample paths of queueing process to analyze the system; we still use the ideas of simulation, but in a different way!
- Formulas for many queueing models
