#+title: Queueing theory assignments
#+SUBTITLE: EBB074A05
#+author: Nicky D. van Foreest
#+date: <2022-01-27 do>

#+STARTUP: indent
#+STARTUP: overview
#+OPTIONS:  toc:nil

#+include: preamble.org

#+PROPERTY: header-args  :session

* Overview

- =assignments.pdf= contains all assignments
- =assignment-answer-template.tex= is the template you should use to hand in your assignment in LaTeX.

* Assignment 6: Simulation with event stacks

<2022-01-27 do> I still have to review this one.

In this simulation I introduce a data structure (a heap queue) to sort numbers, names, and so on, but also /events/.
This is a crucial part to simulate queueing systems because in such systems we move from event to event, from a job arrival to a job departure or to another arrival, and so on.
Next I introduce classes a `thing' to structure information and data.
With this I can define a job as a class.
Finally, I combine heap queues and classes to make a queueing server.
This type of setting up a simulation environment makes it very easy /and/ elegant to simulate queueing systems that operate under different types of scheduling rules, such as `shortest processing time first', or `last-in-first-out'.


- [[https://youtu.be/nW3acIv7Hc8]]
- [[https://youtu.be/qbBBCFhVvGo]]
- [[https://youtu.be/mZS-RX9Ahyg]]
- ~simulations_event_stacks.pdf~


* old stuff
This is old stuff, which I perhaps use another time, but not this year (2022)
** Assignment 4: Empirical distribution functions
I discuss some inefficient and efficient code to compute  an empirical cumulative distribution function (ECDF) of a given set $x$ of measurements. I also include some =matplotlib= functions on how to plot the ECDF.
- https://youtu.be/aKfv908uWqM
- ~2_empirical-distributions.pdf~ contains the code and the plots.
