#+title: Queueing Theory: simulations
#+SUBTITLE: EBB074A05
#+author: Nicky D. van Foreest
#+date: 2020:11:15

#+STARTUP: indent
#+STARTUP: overview
#+OPTIONS:  toc:nil

#+include: preamble.org

#+PROPERTY: header-args  :session

* General info

The idea is to show you how I build up programs in python from scratch to simulate queueing systems.
On purpose I do not use the most nifty coding or python tricks, but I try to stick to simple ideas.
You should know that the general ideas are more important than code syntax.
About using python, I like it, but you can use any other language you like for your own simulations.


Here are two options to run python code in the browser so that you don't have to install python locally (i.e., on your computer):
- [[https://diggyhq.com/][diggy]]
- [[https://colab.research.google.com/notebooks/intro.ipynb][colab]]
I prefer to work within emacs (an editor), and run the code in a terminal. This works much faster and more conveniently, but requires a bit (but not much) of intellectual effort and investment in how to configure things on your computer. If you're interested in the power tools  I use, check out my [[https://ndvanforeest.github.io/tools/][tools page]].

If you copy paste the code below into a jupyter notebook, the code should run more or less as is.

All youtube movies can be found at the channel https://www.youtube.com/playlist?list=PL1CE-7HB8brWuLRhET3zskh1YXWKiUIY_.
Below I include the links to each of the videos organized per section.


For further explanations you should consult my queueing book: https://github.com/ndvanforeest/queueing_book

The questions/problems for each assignment are in the related =pdf= file.

The document =assignment-answer-template.tex= is a template that you can use for making your LaTeX assignment.

* Assignment 1: Simulation in Discrete time

Here I show how to set up  environment in python to simulate queueing systems in discrete time.
- https://youtu.be/DfYxayoQmjYc
- https://youtu.be/D8BIAoBICnw
- https://youtu.be/_BoagRyH5c0
- ~1_queues-simulations-in-discrete-time.pdf~ contains the code and the results.
- ~1_queues-simulations-in-discrete-time.org~ is the org-mode source.


* Assignment 2: Empirical distribution functions
I discuss some inefficient and efficient code to compute  an empirical cumulative distribution function (ECDF) of a given set $x$ of measurements. I also include some =matplotlib= functions on how to plot the ECDF.
- https://youtu.be/aKfv908uWqM
- ~2_empirical-distributions.pdf~ contains the code and the plots.
- ~2_empirical-distributions.org~ is the source


* Assignment 3: Psychiatrists doing intakes

There are 5 psychiatrists doing intakes.
In their current organization, the queue of patients waiting for intakes is way too long, much longer then they like to see.
Here I consider some strategies to deal with this controlling the queue length process, and I use simulation to evaluate how successful these are.

- https://youtu.be/bCU3oP6r-00
- ~3_psychiatrists.pdf~ for code and plots
- ~3_psychiatrists.org~:source



* Assignment 4: Queues in continuous time

I discuss two elegant algorithms to simulate the waiting time process. One is for a system with one server, and jobs are served in the order in which they arrive. The second is for a multi-server FIFO queue.

- Youtube: https://youtu.be/h1OTvdLs9ik
- ~4_queues-simulations-continuous-time.org~
- ~4_queues-simulations-continuous-time.pdf~


* Assignment 5: Supermarket planning, Multi-server queue with dynamically changing arrival rates

Here I apply the code to simulate a supermarkets.
A supermarket can be modeled as a multi-serve queueing system with dynamically changing load.
Because of this the analytical analysis is hard, but with simulation we can get the job done with ease.
The task is to make a plan to determine the number of cashiers we need to prevent the queue from exploding.

- Youtube: [[https://youtu.be/nV4MwjMe3vQ]]
- ~5_multiserver-queue-dynamic-arrival-rates.org~
- ~5_multiserver-queue-dynamic-arrival-rates.pdf~


* Assignment 6: Simulation with event stacks

In this simulation I introduce a data structure (a heap queue) to sort numbers, names, and so on, but also /events/.
This is a crucial part to simulate queueing systems because in such systems we move from event to event, from a job arrival to a job departure or to another arrival, and so on.
Next I introduce classes a `thing' to structure information and data.
With this I can define a job as a class.
Finally, I combine heap queues and classes to make a queueing server.
This makes it very easy to simulate queueing systems that operate under different types of scheduling rules, such as `shortest processing time first', or `last-in-first-out'.


- [[https://youtu.be/nW3acIv7Hc8]]
- [[https://youtu.be/qbBBCFhVvGo]]
- [[https://youtu.be/mZS-RX9Ahyg]]
- ~6_simulations_event_stacks.org~
- ~6_simulations_event_stacks.pdf~


* TODO Things for later years

- Check-in at an airport
- Server interuptions, Batching and setups, non-preemptive outages: adjustments, pre-emptive outages: failures
- MG1, Finite waiting room and  recursions for queue length distribution
- MM1 with setup cost under N policy
- MG1 with setup cost under N policy
